### ISSUE TITLE
Interactive hello world

### ISSUE THREAD

**Issue by yb172** [yb172/code-quest#3]
Good job!

Let's now move to printing to the output instead of `README.md` and make it interactive: the program should first ask the name and then print it back with "Hello".

For example how it might look like:

```bash
go run main.go
Hi, what is your name?
> Yan
Hello, Yan
```

**Comment by mfinikov** [comment]
Should I put this code into new branch or in the main ?

**Comment by yb172** [comment]
Please make a change in a separate branch and then request a PR to merge into main

**Comment by mfinikov** [comment]
Done
