### ISSUE TITLE
Let's make a game

### ISSUE THREAD

**Issue by yb172** [yb172/code-quest#5]
We'll start with the most simple setup:
 * It's a 1D game (meaning we only have one dimension)
 * Player is displayed as `A`
 * Land cell is displayed as `_`
 * Landscape has length of 16 land cells

The game works as follows: when it starts the player is located at the beginning of the landscape:

```
A_______________
```

When &rarr; is pressed player moves to the right:

```
_A______________
```

when &larr; is pressed player moves to the left:
```
A_______________
```

The goal is to move player to the end of the landscape. When it happens the game should print "You won!"

**Comment by mfinikov** [comment]
Should this looks like this?

```
A_______________
[right arrow click]
_A______________
[right arrow click]
___A____________
```

It should send new line every time I press the arrow buttons?

**Comment by yb172** [comment]
Yes it's ok to send a new line on each press
